  const nameAnalysisData = [
    "Always popular",
    "Makes friends easily",
    "Is very helpful",
    "Too hot",
    "Is very attractive",
    "Has a good sense of humor",
    "Is loved by everyone",
    "Very romantic",
    "A little possessive",
    "Is quite dynamic",
    "Shares everything with friends",
    "Admits mistakes easily",
    "Ignores bad things",
    "Does not forgive easily",
    "Gets angry but regains cool very soon",
    "Encourages others",
    "Likes to chill with friends",
    "Always lucky in a relationship",
    "Is very co-operative",
    "Has an appealing personality",
    "Faithful towards family",
    "Is very hardworking",
    "Is very affectionate",
    "Is very adorable",
    "Is extremely lovable",
    "Is very optimistic",
    "Forgives loved ones easily",
    "Has a mysterious personality",
    "Is very open minded",
    "Is quite frank",
    "Is quite straightforward",
    "Is expressive in love",
    "Very focused towards goals",
    "Has an attractive personality",
    "Has a magnetic personality",
    "Is very caring",
    "Is a very loving person",
    "Is quite outgoing",
    "Is very amiable",
    "Selfish at times",
    "Is practical in life",
    "Always respected by others",
    "Respects elders",
    "Is innocent",
    "Self confident",
    "Is a good listener",
    "Has nice communication skills",
    "Fun loving person",
    "Has a sweet smile",
    "Likable personality",
    "Can become a good friend",
    "Trust others easily",
    "Does not compromise easily",
    "Is not very demanding",
    "Is very creative",
    "Has a mesmerizing smile",
    "Positive thinker",
    "Is a gentle person",
    "Is blunt but soft from inside",
    "Has good control on emotions",
    "Quite good looking",
    "Very adventurous",
    "Loves challenges",
    "Loyal in a relationship",
    "Dedicated towards work",
    "Sometimes quite lazy",
    "Is very warmhearted",
    "Compassionate",
    "Is very sensual",
    "An intelligent person",
    "Good at solving problems",
    "Very good crisis handler",
    "Is mature in taking decisions",
    "Is realistic in life",
    "Sensible nature",
    "Helpful personality",
    "Simple living and high thinking",
    "Looks for perfection",
    "Flexible in nature",
    "Accepts change easily",
    "Is very popular amongst friends",
    "Good presence of mind",
    "Is an independent person",
    "Freedom lover",
    "Quite dependable",
    "Is at times emotional",
    "Has a calm nature",
    "Peace lover",
    "Is easygoing in life",
    "Has a very stylish personality",
    "Is an adorable person",
    "Is sincere in work",
    "Is very reliable",
    "Is not a show-off",
    "Great sense of style",
    "Lighthearted",
    "Logical thinker",
    "Pragmatic person",
    "Always energetic",
    "Has a cool exterior",
    "Fast learner",
    "Liked by others",
    "Adapts to situations very well",
    "A little self-centred at times",
    "Is a party animal",
    "Appealing nature",
    "Has a mellow persona",
    "Is punctual",
    "Lively personality",
    "Loves to socialize",
    "Is versatile",
    "Warm and humble",
    "Has beautiful eyes",
    "Is brave",
    "Likes to try new things",
    "Loves to visit new places",
    "Has a pleasing personality",
    "Sometimes jealous",
    "Envied by few people",
    "Admired by peer group",
    "Is very cute",
    "Bubbly personality",
    "Is fun to be around with",
    "Very clever",
    "Is very smart",
    "Delightful to talk with",
    "Does not copy others",
    "Original thinker",
    "Likes to make new friends",
    "Has a good fashion sense",
    "Good entertainer",
    "Cracks funny jokes",
    "Is kind and considerate",
    "Thoughtful person",
    "Is very ambitious",
    "Is a charming person",
    "Is an expressive person",
    "Listens carefully to advice",
    "Is a family person",
    "Respects everybody",
    "Disciplined",
    "Talks politely",
    "Takes responsibility",
    "Thinks positively",
    "Committed towards work",
    "Doesn't get disappointed easily",
    "Motivates friends",
    "Versatile personality",
    "Accepts change in life easily",
    "Can take decisions independently",
    "Very cheerful",
    "Considerate toward others",
    "Well-mannered",
    "Has good judgement",
    "Is competitive",
    "Enthusiastic",
    "Self-assured attitude",
    "Excited about life",
    "Courteous toward others",
    "Jovial personality",
    "Quite honest",
    "Modest in behavior",
    "Interesting person",
    "Is tenderhearted",
    "A little sensitive",
    "Team player",
    "Is receptive and interested in opinions",
    "Is very understanding",
    "Unique approach towards work",
    "Enchanting talker",
    "Has an artistic mind",
    "Always looking for improvement",
    "Knowledgeable person",
    "Is impartial",
    "Is a little short-tempered",
    "Has good stamina",
    "Takes tension easily",
    "Impressive orator",
    "Enjoys taking risks",
    "A little money minded",
    "Prefers stability in life",
    "Can Influence people easily",
    "Lucky with money",
    "Talented individual",
    "Likes to take part in extra-curricular activities",
    "Has a modern taste",
    "Is comfortable talking to new people",
    "Has a wonderful smile",
    "Likes to live lavishly",
    "Does everything with zeal",
    "Is protective",
    "Is a little clumsy",
    "Has a vibrant face",
    "Is talkative",
    "Sometimes stubborn",
    "Is moody at times",
    "Is a cleanliness freak",
    "Daring at times",
    "Does not run after materialistic things",
    "Is a little stingy",
    "Witty and smart",
    "Is very graceful",
    "Is very poised",
    "Is efficient in work",
    "Good at crisis management",
    "Obedient towards elders",
    "Likes to be organized",
    "Is very selective",
    "Likes to spread smiles",
    "Is pretty/handsome",
    "Achieves success easily",
    "Never gives up",
    "Charismatic",
    "Naughty at times",
    "Playful personality",
    "Is highly spiritual",
    "Has sparkling eyes",
    "Good leadership skills",
    "Acts on impulsive",
    "Mature person",
    "Self-indulgent",
    "Brilliant thinker",
    "Intellectual",
    "Sharp minded",
    "Persuasive attitude",
    "Good human being",
    "Is a pioneer",
    "Is very spontaneous",
    "Assertive in nature",
    "Determined in work/studies",
    "Youthful and full of life",
    "Tenacious when required",
    "Good ability to persuade others",
    "Patriotic for the country",
    "Vivacious soul",
    "Magnanimous towards the needy",
    "Majestic presence in a crowd",
    "Indefatigable nature",
    "Intuitive character",
    "Intense thinker",
    "Investigative mind",
    "Courageous spirit",
    "Athletic attitude",
    "Philanthropic nature",
    "Nature lover",
    "Good-humored",
    "Constructive critic",
    "Responds well to feedback",
    "Tireless worker",
    "Prudent in action and thought",
    "Industrious in work and studies",
    "Brainy character",
    "Tolerant attitude",
    "Goal-oriented person",
    "Selfless hence loved by others",
    "Innovative brains",
    "Idealistic yet forward thinking",
    "Modern thinking",
    "Foresighted",
    "Altruistic since birth",
    "Charitable outlook",
    "Imaginative to the core",
    "Spreads joy around",
    "De-stresses others",
    "Sympathetic towards the needy",
    "Free-spirited",
    "Meticulous in whatever you take up",
    "Analytical mind",
    "Alert always",
    "Generous soul",
  ];


  const firstLetter = {
    "A": "You are a very confident person. You lead people with authority. You are constantly in search of adventure and activity. In your work and studies, you dedicate yourself totally.",
    "B": "You are a brave person by nature. Giving up easily is not in your dictionary of words. You are kind and charitable. You cherish the company of your closest friends and family members.",
    "C": "You have a charismatic personality. Your communication skills are exceptional. You stand up for your beliefs and gain self-respect. You have an intelligent mind with astute insight.",
    "D": "You have certain principles which you follow religiously. You always like things to be in order. You get finicky about cleanliness and tidiness. You are born to do business.",
    "E": "You are a compassionate and gentle person. You love your freedom and hate unwanted interference. Your magnetic personality and charming smile win you new friends and fans.",
    "F": "You are a very caring person. You have the incredible ability to make others feel comfortable around you. You believe in doing good deeds without expecting anything in return.",
    "G": "You are a creative individual and a lateral thinker. You rely a lot on your gut instinct. You like learning new things and visiting new places. You are quite religious by nature.",
    "H": "You have an imaginative mind. You prefer to rule rather than be ruled. You are in search of power rather than money. You will be more successful in business than in a job.",
    "I": "You are an understanding person. You empathize with the problems of other people and act accordingly. You are broad-minded and very helpful. Your altruistic nature will take you ahead in life.",
    "J": "You are a bright person. By nature, you are quite honest. Success comes to you because you work very hard without giving up. You have big aspirations in life and will achieve a lot.",
    "K": "You are a self-assured individual. Generally, you are in charge of the situation. You are affectionate towards your loved ones. You are keen to do some meaningful work in life.",
    "L": "Your actions speak louder than your words. You are proactive and are not caught unprepared in any situation. You have a big heart and believe in philanthropy. Your good actions will reap fruit in the future.",
    "M": "You are a very hardworking person. You do not idle away time. Your absolute resolve and self-confidence bring success to your doorstep. You bring change rather than waiting for it to happen.",
    "N": "You are a very intuitive person. You are a fairly talkative person and love to chat with your friends. You are frank with your opinions. You have an artistic side which is somewhat unexplored.",
    "O": "You are a very patient individual and this quality helps you a lot. You tend to excel in your studies. At times, you tend to get emotional. You think for the greater good of the community.",
    "P": "You are a person of much knowledge. You are spiritual in nature. With your words and actions, you command influence over your peers. You have your own unique way of doing things.",
    "Q": "You have a unique personality, quite different from others. You don't follow trends, instead, you set them. You always hold your own in a crowd. There is an aura of mystery around your personality.",
    "R": "You are a very easygoing person. You adopt a humane approach towards others in need. You try to keep stress as much away from you as possible. Living in peace is what you look out for.",
    "S": "You initiate ideas and events. Your positive thinking nature will help you a lot in life. You don't have to strive too much for wealth. Your gracious manners win you many fans.",
    "T": "You are a mentally strong person. You are in constant search of new knowledge to progress in life. People like you for your innocent and helpful nature. You don't go overboard with your emotions.",
    "U": "You love your freedom in life. You prefer to be independent so that no one can control your life. You are generally lucky in whatever decisions you take. Your wit and wisdom are loved by your friends.",
    "V": "You are a very industrious person. Your enthusiasm knows no bounds. You do not rest till the work on hand is complete. You will accomplish a lot in life because of your dynamic nature.",
    "W": "You are a very expressive person. You speak your mind and do not hide things deliberately. Your charming presence is loved by your family and friends. You also protect your personal space.",
    "X": "You are a very sensual person. You seek luxury and pleasure in your life. By nature, you are very indulgent. You manage to flirt very well with the opposite sex.",
    "Y": "You are a freedom lover. You would not accept anyone telling you to do this or not do that. You have an inventive mind. You are not satisfied with conventional things and go for quirky stuff.",
    "Z": "You become a peacemaker whenever there is any conflict among your near and dear ones. By nature, you are an optimistic person. Acting diplomatically helps you come out of difficult situations."
  };


  const nameTrueMeaning = {
    A: ["You are a born leader.", "You have an adventurous streak.", "You are a confident person."],
    B: ["You have a sensitive personality.", "You are very friendly.", "You are a largehearted individual."],
    C: ["You are a clever person.", "You have a sociable nature.", "You are a charming person."],
    D: ["You act in a determined way.", "You have a balanced nature.", "You have a sharp mind."],
    E: ["You have a compassionate heart.", "You have an ingenious mind.", "You love to be independent."],
    F: ["You are softhearted.", "You love to shower your affection on your near ones.", "You are quite reliable in important matters."],
    G: ["You have a strong intuition.", "Wisdom is your forte.", "You are religious at heart."],
    H: ["You have strong business acumen.", "You are a nature loving person.", "You are quite efficient in your work."],
    I: ["You are a refined individual.", "You are polite with others.", "You are an inspirational person."],
    J: ["Your honesty is appreciable.", "You are a brainy person.", "You are known for your kindness."],
    K: ["You have a lot of influence over others.", "Your assertive nature can take you places.", "Your energy levels know no bounds."],
    L: ["You are an exuberant person.", "Smartness is one of your assets.", "You are rational and sensible."],
    M: ["Few people are as hardworking as you are.", "Your self confidence is immense.", "Your clairvoyance can surprise others."],
    N: ["Your extroverted nature does your personality wonders.", "You are a deep thinker.", "You have artistic abilities."],
    O: ["You have a studious temperament.", "Your persistent personality helps you get work done faster.", "You like to help others."],
    P: ["You are a knowledgeable person.", "You have a powerful aura which puts you in command."],
    Q: ["You are quite enthusiastic in your daily life.", "You have strong will power.", "You have an enigmatic personality which attracts others towards you."],
    R: ["You are quite easygoing in life.", "Being charitable and kind comes naturally to you.", "You are quite a sensible person."],
    S: ["You are an attractive person.", "You are lucky with money which is awesome.", "You are mentally strong."],
    T: ["Your lively personality is your plus point.", "Spirituality is ingrained in you.", "You are very romantic at heart."],
    U: ["You are quite social and outgoing.", "You cherish your freedom.", "You are known for your intelligence."],
    V: ["Your indefatigable attitude towards your work is worth praise.", "You are truthful in your dealings.", "You remain faithful in a relationship."],
    W: ["You have an enchanting persona.", "You are able to express your views very clearly.", "You are gregarious and hence have many friends."],
    X: ["You are always in the seek of pleasures in life.", "You are a sensual person.", "You are indulgent by nature."],
    Y: ["You have an inventive streak.", "You love your freedom and don’t like anyone messing with it.", "You have a beautiful aura around you."],
    Z: ["Your diplomacy skills help you in a number of situations.", "You have a sympathetic heart.", "You act as peacemaker whenever there is trouble among your near and dear ones."]
  };
  

  const nameSecretsPositive = {
    A: ["leader", "adventurous", "confident"],
    B: ["sensitive", "friendly", "largehearted"],
    C: ["clever", "sociable", "charming"],
    D: ["determined", "balanced", "sharp"],
    E: ["compassionate", "ingenious", "independent"],
    F: ["softhearted", "affectionate", "reliable"],
    G: ["intuitive", "wise", "religious"],
    H: ["business-minded", "outdoors person", "efficient"],
    I: ["polite", "refined", "inspirational"],
    J: ["honest", "brainy", "kind"],
    K: ["influential", "assertive", "energetic"],
    L: ["exuberant", "smart", "rational"],
    M: ["hardworking", "self confident", "clairvoyant"],
    N: ["extrovert", "imaginative", "artistic"],
    O: ["studious", "persistent", "helpful"],
    P: ["knowledgeable", "powerful", "expressive"],
    Q: ["enthusiastic", "strong-willed", "enigmatic"],
    R: ["easygoing", "charitable", "sensible"],
    S: ["attractive", "lucky with money", "mentally strong"],
    T: ["lively", "spiritual", "romantic"],
    U: ["social", "freedom loving", "intelligent"],
    V: ["indefatigable", "truthful", "faithful"],
    W: ["enchanting", "eloquent", "gregarious"],
    X: ["pleasure seeker", "indulgent", "sensual"],
    Y: ["inventive", "loves freedom", "beautiful"],
    Z: ["diplomatic", "sympathetic", "peacemaker"]
  };
  
  const nameSecretsNegative = {
    A: ["arrogant"],
    B: ["aggressive"],
    C: ["inattentive"],
    D: ["uncompromising"],
    E: ["unreliable"],
    F: ["gloomy"],
    G: ["cynical"],
    H: ["egoistic"],
    I: ["cowardly"],
    J: ["lazy"],
    K: ["discontented"],
    L: ["clumsy"],
    M: ["hasty"],
    N: ["jealous"],
    O: ["melodramatic"],
    P: ["self-absorbed"],
    Q: ["boring"],
    R: ["short-tempered"],
    S: ["reckless"],
    T: ["gullible"],
    U: ["selfish"],
    V: ["unpredictable"],
    W: ["greedy"],
    X: ["unfaithful"],
    Y: ["indecisive"],
    Z: ["foolhardy"]
  };


    module.exports = { nameAnalysisData, firstLetter ,nameTrueMeaning , nameSecretsPositive, nameSecretsNegative  };